# Generated by Django 4.2.2 on 2023-12-13 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveJobPostings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('job_description', models.TextField()),
                ('date_posted', models.DateField()),
                ('application_deadline', models.DateField()),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Applicants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_information', models.CharField(max_length=100)),
                ('application_date', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('applied_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.activejobpostings')),
            ],
        ),
        migrations.CreateModel(
            name='Placements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement_date', models.DateField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('client_company', models.CharField(max_length=100)),
                ('placement_status', models.CharField(max_length=50)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.applicants')),
                ('job_posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.activejobpostings')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyInterviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_date', models.DateField()),
                ('interviewers', models.CharField(max_length=200)),
                ('interview_outcome', models.CharField(max_length=100)),
                ('comments', models.TextField()),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.applicants')),
                ('job_posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.activejobpostings')),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
