# Generated by Django 4.2.2 on 2023-12-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_interviewer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklyinterviews',
            name='interviewers',
        ),
        migrations.AddField(
            model_name='weeklyinterviews',
            name='interviewers',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
